### ISSUE TITLE
Docker で開発環境構築できない

### ISSUE THREAD

**Issue by shunyama** [ingage/diary-rails#19]
@shunyama の個人の PC で docker を用いて開発環境構築しようとしましたが、できませんでした。
## エラー内容
`docker-compose up` すると、アプリケーションのコンテナ起動の際に以下のログが出る。
```
journally-web | `/journally` is not writable.
journally-web | Bundler will use `/tmp/bundler20210623-8-1tm5ua8' as your home directory temporarily.
journally-webpack | WARNING: 13 repetitive deprecation warnings omitted.
journally-webpack | 
journally-web | /usr/local/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /journally/tmp/cache (Errno::EACCES)
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:211:in `each'
journally-web | 	from /usr/local/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/store.rb:84:in `dump_data'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/store.rb:58:in `commit_transaction'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/store.rb:49:in `block in transaction'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/store.rb:45:in `synchronize'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/store.rb:45:in `transaction'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/cache.rb:139:in `push_paths_locked'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/cache.rb:122:in `block in reinitialize'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/cache.rb:116:in `synchronize'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/cache.rb:116:in `reinitialize'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache/cache.rb:16:in `initialize'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache.rb:44:in `new'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/load_path_cache.rb:44:in `setup'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap.rb:62:in `setup'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap.rb:108:in `default_setup'
journally-web | 	from /usr/local/bundle/gems/bootsnap-1.7.4/lib/bootsnap/setup.rb:4:in `<top (required)>'
journally-web | 	from /journally/config/boot.rb:6:in `require'
journally-web | 	from /journally/config/boot.rb:6:in `<top (required)>'
journally-web | 	from /journally/bin/rails:6:in `require_relative'
journally-web | 	from /journally/bin/rails:6:in `<top (required)>'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
journally-web | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
journally-web | 	from /journally/bin/spring:12:in `require'
journally-web | 	from /journally/bin/spring:12:in `block in <top (required)>'
journally-web | 	from <internal:kernel>:90:in `tap'
journally-web | 	from /journally/bin/spring:9:in `<top (required)>'
journally-web | 	from bin/rails:4:in `load'
journally-web | 	from bin/rails:4:in `<main>'
journally-web exited with code 1
```
## 手順
[開発環境構築](https://github.com/ingage/diary-rails#%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89) に書かれたとおりにやりました。
1. git clone する
2. `.env` と `.env.local` を作成する（前準備に書かれてるものをそのままコピペ。値もちゃんとしたデータではない）
3. `docker-compose build` を実行。うまくいった。
4. `docker-compose up -d` を実行。creating.. Done と4回出た。うまくいった。
5. http://localhost:3007 や http://localhost:3007/dynamodb にアクセスするも、「このサイトにアクセスできません」と出る。
6. `docker-compose ps` すると、4つとも up になっている。（ただし最初だけみたい）
7. 何回リロードしてもアクセスできないため、`docker-compose down` し、再度 `docker-compose up` してみる。
8. application コンテナの立ち上げでエラー発生を確認。

## 調査
石田さん・原野さんから、bash でコンテナ内に入って  /journally/tmp 、 /journally/tmp/cache のディレクトリが存在するか否か、存在するなら権限を確認するよう言われたのでその調査結果です。

`docker-compose exec web /bin/bash` を実行すると、一瞬コンテナ内に入れるがすぐにホストに戻される。

`docker-compose ps` すると、`journally-web` のみ restarting となってる。

上記手順にも記載したが、`docker-compose up -d` 直後のみ `journally-web` は `up` で、もう一度 `ps` を叩くと以後ずっと `restarting` となっている。

### PC の 環境
```sh
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=20.1
DISTRIB_CODENAME=ulyssa
DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
```
```sh
$ docker -v
Docker version 20.10.7, build f0df350
```

**Comment by shunyama** [comment]
環境構築できました！ありがとうございました！ > @kizashi1122 

## 方法
Dockerfile の uid をホストOSの `uid` へ変更し、再度 `docker-compose up -d --build` しただけ。

ホストOSの `uid` を調べて…
```
$ id -u
1000
```

Dockerfile の L36 の `adduser -uid 999` を `adduser -uid 1000` へ変更。
その後、`docker-compose up -d --build` したらできた。
